baseURL: 'https://nimgroup.github.io/'
title: NIMG
theme: PaperMod

enableInlineShortcodes: true
enableRobotsTXT: true
enableEmoji: true
pagination:
  pagerSize: 20

taxonomies:
  tag: tags

menu:
  main:
    - name: About
      url: about/
      weight: 1
    - name: Research
      url: research/
      weight: 2
    - name: Publication
      url: publications/
      weight: 3
    - name: Member
      url: members/
      weight: 4
    - name: Photos
      url: photos/
      weight: 5
    - name: Source
      url: source/
      weight: 6
    - name: News
      url: news/
      weight: 7
#    - name: Contact
#      url: contact/
#      weight: 8

params:
  description: 'NIMG researches AI and machine learning for intelligent medicine, with a focus on neural navigation and image-enabled brain-computer interfaces.'
  author: NIMG
  # googleAnalyticsID: "G-XXXXX"
  DateFormat: 'January 2006'
  defaultTheme: light
  hideFooter: false
  disableThemeToggle: true
  ShowShareButtons: false
  ShowReadingTime: false
  disableSpecial1stPost: true
  disableAnchoredHeadings: true
  ShowPostNavLinks: false
  ShowBreadCrumbs: false
  ShowCodeCopyButtons: true
  ShowAllPagesInArchive: false
  MainSections: ['publications', 'research', 'source', 'news']
  ShowToc: false
  disableScrollToTop: true
  TocOpen: true
  ShowWordCount: false
  UseHugoToc: true
  comments: true
  math: true
  profileMode:
    enabled: true
    title: 神经影像智能理解实验室（NIMG@NJUST）
    subtitle: '我们聚焦脑科学 × AI × 智能医学交叉前沿，探索脑连接组、脑机接口、精准神经导航、人脑数字孪生等方向。这里不迷信刷榜，不沉迷堆模型，而是坚持解决真实问题，打造可解释、可复现、可落地的技术。我们希望，每一个灵感都能成长为一篇论文、一套代码、一个开源工具、一款产品，甚至一次改变临床实践的创新。如果你热爱科研、喜欢写代码、敢于探索未知，NIMG 或许正是你下一段旅程的起点。'
    imageUrl: 'logo.png'
    imageWidth: 160
    imageHeight: 115
    buttons:
      - name: About
        url: about/
      - name: Research
        url: research/
      - name: Publication
        url: publications/
      - name: Member
        url: members/
      - name: Photos
        url: photos/
      - name: Source
        url: source/
      - name: News
        url: news/
#      - name: Contact
#        url: contact/

  socialIcons:
    #- name: CV
    #  url: cv.pdf
    - name: Email
      url: mailto:dr.yewu@outlook.com
    #- name: Zoom
    #  url: https://www.zoom.us/my/igelfeld
    - name: Location
      url: location/
    - name: Office Hours
      url: officehours/
    - name: Google Scholar
      url: https://scholar.google.com/citations?user=soMcNA8AAAAJ
    - name: GitHub
      url: https://github.com/nimgroup
    #- name: Substack
    #  url: https://pmichaillat.substack.com
    #- name: YouTube
    #  url: https://www.youtube.com/@pmichaillat
    - name: Twitter
      url: https://x.com/wuye4567
    #- name: Bluesky
    #  url: https://bsky.app/profile/pmichaillat.bsky.social
    - name: ORCID
      url: https://orcid.org/0000-0002-8643-4023

  assets:
    disableScrollBarStyle: true
  cover:
    hiddenInList: false
    hiddenInSingle: true
  label:
    text: 'NIMG'
    icon: logo.png
    iconHeight: 40
    iconWidth: 56

markup:
  goldmark:
    renderer:
      unsafe: true
  highlight:
    guessSyntax: true
    style: autumn
  tableOfContents:
    endLevel: 2
    ordered: false
    startLevel: 2
